Create Fidget Spinner.py
ron2111/Hacktoberfest2021_awesome-projects pull request #37
Opened 2021-09-30 19:58 UTC by aarshita02

Issue #2 
Created a fidget spinner in python.

2021-09-30 20:01 UTC, ron2111 requested changes
Update project_doc.md with your project's description& add your name in the list of contributors in README.md

2021-10-01 05:17 UTC, aarshita02 commented
Done!

2021-10-01 06:49 UTC, ron2111 commented
resolve the merge conflicts

2021-10-01 07:04 UTC, aarshita02 commented
resolved!

2021-10-01 09:36 UTC, merged